edition = "2024"

# Keep formatting width preferences
max_width = 150
use_small_heuristics = "Default"

# Stable, safe rewrites
use_try_shorthand = true
use_field_init_shorthand = true

# Replace deprecated option
fn_params_layout = "Compressed"
