name: ci
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: clippy, rustfmt
      - name: Run clippy
        run: cargo clippy
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Build
        run: cargo build
      - name: Install nightly for docs
        uses: dtolnay/rust-toolchain@nightly
      - name: Build docs (all features)
        run: RUSTDOCFLAGS="--cfg docsrs" cargo doc --all-features --no-deps

  example_basic:
    name: Example | Basic
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: clippy, rustfmt
      - name: Install trunk
        uses: taiki-e/install-action@v2
        with:
          tool: trunk
      - name: Build example
        run: cd examples/basic && trunk build
